services:
  tweet_service_production:
    container_name: Mini_Tweeter_tweet_service_production
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - ENVIRONMENT=develop
      - RPC_PORT=8083
      - HTTP_PORT=8009
      - POSTGRES_HOST=database_production
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=mini_tweeter_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 10s
    restart: on-failure
    networks:
      - Mini-Tweeter-network

networks:
  Mini-Tweeter-network:
    external: true